### ISSUE TITLE
mce-table-buttons terminated

### ISSUE THREAD

**Issue by Retroperra** [municipio-se/municipio-boilerplate-standard#2]
It appears that mce-table-buttons is closed from 11 mars this year.

Read on: https://wordpress.org/plugins/mce-table-buttons/

How can I replace that dependencie? Just bypass it?

**Comment by jeanfredrik** [comment]
This is fixed in [municipio-se/municipio-bundle-standard@5.0.1](https://github.com/municipio-se/municipio-bundle-standard/releases/tag/5.0.1)
